Vroemmm/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vroemmm.Models;
using Vroemmm.Logic;
using Google.Apis.Authentication;
using Vroemmm.GoogleAuth;
using Google.Apis.Calendar.v3;

namespace Vroemmm.Controllers
{
    public partial class CalendarController : Controller
    {
        public virtual ActionResult SelectCalendar()
        {
            try
            {
                var calendarService = this.GetAgendaService();
                var importer = new AgendaImporter(calendarService);
                var model = importer.GetCalendarsModel();
                if (model.Count() == 1)
                {
                    // only one agenda, so select it by default and move on the other 
                }
                return View(model);
            }
            catch (NoAuthenticatorException)
            {
                return RedirectToRoute("GoogleAuthentication", new { callbackurl = Request.Url });
            }
        }

        public virtual ActionResult SelectEvents(string calendarId)
        {
            var model = new SelectEventsModel()
            {
                CalendarId = calendarId
            };
            return View(model);
        }

        public virtual ActionResult ShowEvents(string calendarId)
        {
            try
            {
                var calendarService = this.GetAgendaService();
                var importer = new AgendaImporter(calendarService);
                var model = importer.GetEventsModel(calendarId);
                Session["eventModel"] = model;
                return View(model);
            }
            catch (NoAuthenticatorException)
            {
                return RedirectToRoute("GoogleAuthentication", new { callbackurl = Request.Url });
            }
        }
    }
}

Vroemmm/Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vroemmm.Logic;
using Vroemmm.Models;
using Vroemmm.GoogleAuth;

namespace Vroemmm.Controllers
{
    public partial class TravelController : Controller
    {
        private readonly IDistanceCalculator distanceCalculator;
        private readonly RouteCalculator routeCalculator;
        public TravelController(IDistanceCalculator distanceCalculator)
        {
            this.distanceCalculator = distanceCalculator;
            this.routeCalculator = new RouteCalculator(distanceCalculator);
        }

        public virtual ActionResult Index(string calendarId, int year, int month)
        {
            try
            {
                var calendarService = this.GetAgendaService();
                var importer = new AgendaImporter(calendarService);
                var events = importer.GetEventsModel(calendarId);

                var locationOptimizer = new LocationOptimizer();
                events = locationOptimizer.OptimizeLocations(events);

                var start = new DateTime(year, month, 1);
                var end = start.AddMonths(1);
                var eventsOfSelectedMonth = events.Where(e => e.Start >= start && e.End <= end);

                var routes = routeCalculator.CalculateRoutes(eventsOfSelectedMonth, "Van koetsveldstraat 39, Utrecht");
                var model = routeCalculator.CalculateTravelCosts(routes);

                return View(model);
            }
            catch (NoAuthenticatorException)
            {
                return RedirectToRoute("GoogleAuthentication", new { callbackurl = Request.Url });
            }


        }
    }
}

Vroemmm/Views/Calendar/SelectCalendar.cshtml
@model IEnumerable<Vroemmm.Models.CalendarModel>

@{
    ViewBag.Title = "Selecteer de kalender die je wilt gebruiken";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "SelectEvents", new { calendarId = item.Id })
        </td>
    </tr>
}

</table>

Vroemmm/Views/Calendar/SelectEvents.cshtml
@model Vroemmm.Models.SelectEventsModel

@{
    ViewBag.Title = "Selecteer de maand waarvan je de reiskosten wilt bereken";
}

<h2>@ViewBag.Title</h2>

@for (int i = 0; i < 12; i++)
{
    var date = DateTime.Now.AddMonths(-i);
    <div>
        @Html.ActionLink(date.ToString("MMMM"), "Index", "Travel", new {calendarId = Model.CalendarId, year = date.Year, month = date.Month }, null)
    </div>
}

Vroemmm/Views/Calendar/ShowEvents.cshtml
@model IEnumerable<Vroemmm.Models.EventModel>

@{
    ViewBag.Title = "Agenda items";
}

<h2>@ViewBag.Title</h2>

@Html.ActionLink("Bereken reiskosten", "Index", "Travel")

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Start)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.End)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Start)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.End)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Summary)
        </td>
    </tr>
}

</table>